# Generated by Django 2.2.16 on 2022-04-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.CharField(max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='description',
            field=models.CharField(max_length=3000, null=True, verbose_name='Описание'),
        ),
    ]
