# Generated by Django 2.2.16 on 2022-04-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0002_auto_20220405_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='year',
            field=models.IntegerField(default=2011, help_text='Введите год релиза', verbose_name='Год релиза'),
            preserve_default=False,
        ),
    ]
