# Generated by Django 2.2.16 on 2022-04-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0002_auto_20220406_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
