# Generated by Django 2.2.16 on 2022-04-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0003_titles_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
