# Generated by Django 2.2.16 on 2022-04-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220404_1710'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_commenting',
        ),
        migrations.RemoveConstraint(
            model_name='comment',
            name='user_cant_commite_yourself',
        ),
    ]
