# Generated by Django 2.2.16 on 2022-04-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220404_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-pub_date']},
        ),
    ]
