# Generated by Django 2.2.16 on 2022-04-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220409_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='genre',
            new_name='genres',
        ),
    ]
