# Generated by Django 2.2.16 on 2022-04-10 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220410_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genretitle',
            old_name='genre',
            new_name='genres',
        ),
    ]
