# Generated by Django 2.2.16 on 2022-04-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220410_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-year'], 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.RenameField(
            model_name='genretitle',
            old_name='genres',
            new_name='genre',
        ),
    ]
